Repository SuSang-YuHee/Debate-Ducks-Server, pull requests merged in 2022-07, with the labels that each got.

#25 이메일 발신 기능 설정 변경
  src/config/emailConfig.ts
  src/email/email.service.ts
  src/users/users.controller.ts
Labels: Modify

#26 토론 컨트롤러, 서비스 구현
  src/app.module.ts
  src/debates/DebateInfo.ts
  src/debates/debates.controller.ts
  src/debates/debates.module.ts
  src/debates/debates.service.ts
  src/debates/dto/create-debate.dto.ts
  src/debates/dto/update-debate.dto.ts
  src/debates/entity/debate.entity.ts
  src/main.ts
Labels: Add, Update, Modify

#28 유저와 토론 관계 설정
  src/debates/DebateInfo.ts
  src/debates/debates.module.ts
  src/debates/debates.service.ts
  src/debates/entity/debate.entity.ts
  src/migrations/1657546475479-CreateTable.ts
  src/migrations/1657699728338-CreateTable.ts
  src/users/entity/user.entity.ts
Labels: Add, Modify, Delete

#30 팩트체크 생성 및 구현
  src/app.module.ts
  src/debates/debates.module.ts
  src/debates/entity/debate.entity.ts
  src/factchecks/FactcheckInfo.ts
  src/factchecks/dto/create-factcheck.dto.ts
  src/factchecks/dto/update-factcheck.dto.ts
  src/factchecks/entity/factcheck.entity.ts
  src/factchecks/factchecks.controller.ts
  src/factchecks/factchecks.module.ts
  src/factchecks/factchecks.service.ts
  src/migrations/1657808062193-CreateTable.ts
  src/users/entity/user.entity.ts
  src/users/users.module.ts
Labels: Add, Update

#31 투표 생성 및 구현
  src/app.controller.spec.ts
  src/app.module.ts
  src/debates/entity/debate.entity.ts
  src/users/entity/user.entity.ts
  src/users/users.controller.spec.ts
  src/votes/VoteInfo.ts
  src/votes/dto/create-vote.dto.ts
  src/votes/dto/update-vote.dto.ts
  src/votes/entity/vote.entity.ts
  src/votes/votes.controller.ts
  src/votes/votes.module.ts
  src/votes/votes.service.ts
Labels: Add, Update, Delete

#32 좋아요 생성 및 구현
  package-lock.json
  package.json
  src/app.module.ts
  src/debates/entity/debate.entity.ts
  src/hearts/dto/create-heart.dto.ts
  src/hearts/entities/heart.entity.ts
  src/hearts/hearts.controller.ts
  src/hearts/hearts.module.ts
  src/hearts/hearts.service.ts
  src/users/entity/user.entity.ts
Labels: Add, Update

#33 댓글 생성 및 구현
  src/app.module.ts
  src/comments/comments.controller.ts
  src/comments/comments.module.ts
  src/comments/comments.service.ts
  src/comments/dto/create-comment.dto.ts
  src/comments/dto/update-comment.dto.ts
  src/comments/entities/comment.entity.ts
  src/debates/entity/debate.entity.ts
  src/users/entity/user.entity.ts
Labels: Add, Update

#34 Feat/record
  src/events/events.gateway.ts
  src/events/utils.ts
Labels: Add, Change, Update, Modify, Delete

#36 알람 생성 및 구현
  src/alarms/alarms.controller.ts
  src/alarms/alarms.module.ts
  src/alarms/alarms.service.ts
  src/alarms/dto/create-alarm.dto.ts
  src/alarms/dto/update-alarm.dto.ts
  src/alarms/entities/alarm.entity.ts
  src/app.module.ts
  src/users/entity/user.entity.ts
Labels: Add, Update

#37 cors 설정
  src/main.ts
Labels: Update

#38 마이그레이션 파일 업데이트
  src/migrations/1657808062193-CreateTable.ts
  src/migrations/1657982473632-CreateTable.ts
Labels: Update

#39 토론 조회 기능 업데이트 및 변수명 수정
  src/debates/debates.controller.ts
  src/debates/debates.service.ts
  src/debates/dto/create-debate.dto.ts
Labels: Update, Modify

#40 토론 업데이트 기능 추가 구현 및 일부 수정 사항 적용
  src/debates/debates.controller.ts
  src/debates/debates.service.ts
  src/debates/dto/update-debate.dto.ts
  src/debates/entity/debate.entity.ts
Labels: Update, Modify

#41 토론 서비스 추가 구현
  src/debates/debates.controller.ts
  src/debates/debates.service.ts
  src/debates/dto/get-debates-forum.dto.ts
  src/debates/dto/search-debates-forum.dto.ts
Labels: Add, Update

#42 댓글 조회 추가 구현
  src/comments/comments.controller.ts
  src/comments/comments.service.ts
  src/comments/entities/comment.entity.ts
  src/debates/debates.service.ts
Labels: Update

#43 좋아요 조회 구현
  src/hearts/hearts.controller.ts
  src/hearts/hearts.service.ts
Labels: Update

#44 좋아요 CRUD 추가 구현 및 서비스 일부 기능 추가
  src/comments/comments.controller.ts
  src/comments/comments.service.ts
  src/comments/dto/update-comment.dto.ts
Labels: Update

#45 좋아요 기능 수정
  src/hearts/hearts.controller.ts
  src/hearts/hearts.service.ts
Labels: Update

#47 투표 기능 구현
  src/votes/dto/create-vote.dto.ts
  src/votes/dto/update-vote.dto.ts
  src/votes/votes.controller.ts
  src/votes/votes.service.ts
Labels: Update

#48 반환타입, 값 수정 및 dto 수정
  src/comments/comments.controller.ts
  src/comments/comments.service.ts
  src/comments/dto/create-comment.dto.ts
  src/factchecks/dto/create-factcheck.dto.ts
  src/factchecks/factchecks.controller.ts
  src/factchecks/factchecks.service.ts
  src/hearts/dto/create-heart.dto.ts
  src/hearts/hearts.controller.ts
  src/hearts/hearts.service.ts
Labels: Modify

#49 토론 조회 기능 업데이트
  src/debates/debates.controller.ts
  src/debates/debates.module.ts
  src/debates/debates.service.ts
Labels: Update

#51 토론 조회 업데이트
  src/debates/debates.controller.ts
  src/debates/debates.service.ts
Labels: Update

#52 에러 처리
  src/debates/debates.service.ts
  src/hearts/hearts.service.ts
  src/votes/votes.controller.ts
  src/votes/votes.service.ts
Labels: Update

#53 유저 모듈 업데이트
  .gitignore
  package-lock.json
  package.json
  src/users/UserInfo.ts
  src/users/dto/update-user.dto.ts
  src/users/entity/user.entity.ts
  src/users/users.controller.ts
  src/users/users.service.ts
  src/utils/image-storage.ts
Labels: Add, Update

#54 ormconfig 환경변수 적용
  ormconfig.js
  ormconfig.json
Labels: Update

#55 유저 조회 수정
  src/users/UserInfo.ts
  src/users/entity/user.entity.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: Modify

#56 누락된 반환 타입 기입
  src/users/users.controller.ts
Labels: Update

#57 토론 엔티티 및 모듈 수정
  src/debates/debates.controller.ts
  src/debates/debates.service.ts
  src/debates/entity/debate.entity.ts
Labels: Modify

#58 댓글 모듈 dto 설정
  src/comments/comments.controller.ts
  src/comments/comments.service.ts
  src/comments/dto/get-comments.dto.ts
Labels: Add, Update

#59 팩트체크 모듈 콘솔 로그 삭제
  src/factchecks/factchecks.controller.ts
Labels: Modify

#60 좋아요 요청 타입 수정 및 dto 설정
  src/hearts/hearts.controller.ts
  src/hearts/hearts.service.ts
Labels: Modify

#61 투표 여부 기능 생성 및 구현
  src/votes/dto/is-voted.dto.ts
  src/votes/votes.controller.ts
  src/votes/votes.service.ts
Labels: Add, Update

#62 Swagger 임시 적용
  package-lock.json
  package.json
  src/main.ts
  src/users/users.controller.ts
Labels: Setting

#63 투표 여부 조회 수정
  src/votes/votes.controller.ts
  src/votes/votes.service.ts
Labels: Modify

#64 유저 컨트롤러 Swagger 적용
  src/users/UserInfo.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/dto/user-info.dto.ts
  src/users/dto/user-login.dto.ts
  src/users/dto/verify-email.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: Update, Modify

#65 토론 컨트롤러에 Swagger 적용
  src/debates/debates.controller.ts
  src/debates/dto/create-debate.dto.ts
  src/debates/dto/get-debates-forum.dto.ts
  src/debates/dto/search-debates-forum.dto.ts
  src/debates/dto/update-debate.dto.ts
Labels: Update

#66 Swagger 적용
  src/main.ts
Labels: Update

#67 댓글 API Swagger 적용
  src/comments/comments.controller.ts
  src/comments/dto/create-comment.dto.ts
  src/comments/dto/get-comments.dto.ts
  src/comments/dto/update-comment.dto.ts
Labels: Update

#68 팩트체크 API Swagger 적용
  src/factchecks/dto/create-factcheck.dto.ts
  src/factchecks/dto/update-factcheck.dto.ts
  src/factchecks/factchecks.controller.ts
Labels: Update, Docs

#69 좋아요 API Swagger 적용
  src/hearts/dto/create-heart.dto.ts
  src/hearts/dto/heart.dto.ts
  src/hearts/hearts.controller.ts
  src/hearts/hearts.service.ts
Labels: Update, Modify, Docs

#71 요구사항에 따른 수정 및 변경 사항 적용
  src/comments/comments.service.ts
  src/comments/dto/get-comments.dto.ts
  src/debates/DebateInfo.ts
  src/users/dto/user-info.dto.ts
  src/users/entity/user.entity.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: Update, Modify

#72 불필요한 임포트 삭제
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: Fix

#73 댓글 리스트 조회 기능 수정
  src/comments/comments.controller.ts
  src/comments/comments.service.ts
  src/comments/dto/get-comments-response.dto.ts
Labels: Add, Modify

#74 마지막 페이지 여부 수정
  src/comments/comments.service.ts
Labels: Modify

#75 유저 정보 조회 기능 수정
  src/users/dto/user-info.dto.ts
  src/users/users.service.ts
Labels: Modify

#76 좋아요 누른 토론 리스트 조회 기능 구현
  ormconfig.js
  src/debates/debates.service.ts
  src/debates/dto/create-debate.dto.ts
  src/debates/dto/search-debates-forum.dto.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: Update, Modify

#78 토론 서비스 쿼리 파라미터 한글 깨짐 현상 수정
  src/debates/debates.service.ts
Labels: Modify

#79 lastPage 수정
  src/comments/comments.service.ts
  src/debates/debates.service.ts
  src/users/users.service.ts
Labels: Fix

#81 유저 정보, 이미지 조회 기능 수정
  src/main.ts
  src/users/entity/user.entity.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: Modify

#82 토론 리스트 조회 기능 수정
  src/debates/debates.controller.ts
  src/debates/debates.service.ts
  src/debates/dto/get-debates-forum.dto.ts
  src/debates/dto/search-debates-forum.dto.ts
Labels: Modify

#83 토론 좋아요 수 기능 보완
  src/debates/debates.service.ts
  src/debates/dto/create-debate.dto.ts
  src/debates/entity/debate.entity.ts
  src/hearts/hearts.service.ts
Labels: Modify

#84 토론 조회 기능 수정
  src/debates/DebateInfo.ts
  src/debates/debates.service.ts
Labels: Modify
