Repository SuSang-YuHee/Debate-Ducks-Server, pull requests merged in 2022-08, with the labels that each got.

#85 토론 dto 유효성 검사 및 수정 기능 수정
  src/debates/DebateInfo.ts
  src/debates/debates.controller.ts
  src/debates/debates.service.ts
  src/debates/dto/create-debate.dto.ts
  src/debates/dto/debate-info-response.dto.ts
  src/debates/dto/get-debates-forum.dto.ts
  src/debates/entity/debate.entity.ts
Labels: Add, Modify, Delete

#86 댓글 dto 유효성 검사 설정
  src/comments/comments.controller.ts
  src/comments/dto/create-comment.dto.ts
  src/comments/dto/get-comments-response.dto.ts
  src/comments/dto/get-comments.dto.ts
  src/comments/dto/update-comment.dto.ts
  src/comments/entities/comment.entity.ts
  src/debates/dto/update-debate.dto.ts
Labels: Update, Modify

#87 유저 dto 유효성 검사 추가 설정
  src/users/dto/update-user.dto.ts
  src/users/dto/user-info-response.dto.ts
  src/users/dto/user-login.dto.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: Add, Update, Modify, Delete

#88 투표 dto 유효성 검사 추가 및 수정 기능 수정
  src/votes/dto/create-vote.dto.ts
  src/votes/dto/get-vote-count-response.dto.ts
  src/votes/dto/is-voted-response.dto.ts
  src/votes/dto/is-voted.dto.ts
  src/votes/dto/update-vote.dto.ts
  src/votes/votes.controller.ts
  src/votes/votes.service.ts
Labels: Add, Update, Modify

#89 팩트체크, 좋아요 dto 유효성 검사 추가
  src/factchecks/dto/create-factcheck.dto.ts
  src/factchecks/dto/update-factcheck.dto.ts
  src/hearts/dto/heart.dto.ts
Labels: Update

#90 타임존 설정 및 토큰 정보 설정
  ormconfig.js
  package.json
  src/alarms/alarms.controller.ts
  src/auth/auth.service.ts
Labels: Update, Modify

#91 엔티티 칼럼 수정 및 dto 검사 수정
  src/debates/dto/create-debate.dto.ts
  src/factchecks/entity/factcheck.entity.ts
Labels: Modify

#92 비밀번호 암호화 및 변경 기능 추가, 요청사항에 따른 dto, entity 수정
  package-lock.json
  package.json
  src/users/dto/create-user.dto.ts
  src/users/dto/update-user-nickname.dto.ts
  src/users/dto/update-user-password.dto.ts
  src/users/entity/user.entity.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: Add, Update, Modify

#93 dto 수정 및 토론 수정, 삭제 삭제 되면 안되는 경우 추가
  src/comments/dto/get-comments.dto.ts
  src/debates/debates.service.ts
  src/debates/dto/get-debates-forum.dto.ts
  src/hearts/dto/heart.dto.ts
  src/votes/dto/is-voted.dto.ts
Labels: Modify

#94 토론 종료 로직 추가
  src/events/events.gateway.ts
Labels: Update, Fix, Delete

#96 토론 비디오 업데이트 수정
  package.json
  src/debates/debates.service.ts
Labels: Update, Modify

#97 Event module 코드 정돈
  src/events/events.gateway.ts
  src/events/utils.ts
Labels: Modify

#101 댓글 - Status Code 설정 및 예외 처리 추가 구현
  src/comments/comments.controller.ts
  src/comments/comments.service.ts
Labels: Update

#102 토론 - Status Code 설정 및 예외 처리 추가 구현
  src/debates/debates.controller.ts
  src/debates/debates.service.ts
Labels: Update

#103 팩트체크 - Status Code 설정 및 예외 처리 추가 구현
  src/factchecks/factchecks.controller.ts
  src/factchecks/factchecks.service.ts
Labels: Update

#104 Status Code 설정 및 예외 처리 추가 구현
  src/hearts/hearts.controller.ts
  src/hearts/hearts.service.ts
  src/votes/votes.controller.ts
  src/votes/votes.service.ts
Labels: Update

#105 Swagger Response 추가 작성
  src/comments/comments.controller.ts
  src/debates/debates.controller.ts
  src/factchecks/factchecks.controller.ts
  src/users/users.controller.ts
Labels: Update, Modify

#106 merge to main
  README.md
  src/comments/comments.controller.ts
  src/comments/comments.service.ts
  src/debates/debates.controller.ts
  src/debates/debates.service.ts
  src/events/events.gateway.ts
  src/events/utils.ts
  src/factchecks/factchecks.controller.ts
  src/factchecks/factchecks.service.ts
  src/hearts/hearts.controller.ts
  src/hearts/hearts.service.ts
  src/users/users.controller.ts
  src/users/users.service.ts
  src/votes/votes.controller.ts
  src/votes/votes.service.ts
Labels: Merge

#107 불필요한 라인 삭제 및 헬스 체크 배포 주소 추가
  src/alarms/alarms.controller.ts
  src/debates/debates.module.ts
  src/factchecks/factchecks.controller.ts
  src/health-check/health-check.controller.ts
  src/hearts/dto/heart.dto.ts
  src/hearts/hearts.controller.ts
Labels: Modify

#108 리드미 수정
  README.md
Labels: Docs

#110 배포 자동화 시점 병합
  README.md
  src/alarms/alarms.controller.ts
  src/app.module.ts
  src/debates/debates.module.ts
  src/debates/dto/debate-info-response.dto.ts
  src/factchecks/factchecks.controller.ts
  src/health-check/health-check.controller.ts
  src/hearts/dto/heart.dto.ts
  src/hearts/hearts.controller.ts
  src/main.ts
  src/users/dto/update-user-nickname.dto.ts
  src/users/users.controller.ts
Labels: Merge

#111 [Hotfix] 잘못된 예외 처리 제거
  src/debates/debates.service.ts
Labels: Fix
